version: '3.7'

services:
  redis:
    image: redis:2.8
    restart: always
    ports:
      - 6379:6379
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    #command: gunicorn test_project.wsgi -b 0.0.0.0:8000
    #command: daphne test_project.asgi:application
    command: daphne -p 8000 --bind 0.0.0.0 -v2 test_project.asgi:application
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  
volumes:
  postgres_data:
